### ISSUE TITLE
GCMReceiver not calling up

### ISSUE THREAD

**Issue by AtulaGuleria** [realtime-framework/MessagingAndroidChat#17]
Hi, I am able to get messages back from server but without notification. Gcm receiver is never called up.

**Comment by realtime-framework** [comment]
Did you configure your Google API key in the Realtime Account Management website for your application key? If not please follow this guide http://messaging-public.realtime.co/documentation/starting-guide/mobilePushGCM.html.

I'm closing the issue for now but feel free to reopen if necessary.
