### ISSUE TITLE
Error when run on android jelly bean 4.1.2

### ISSUE THREAD

**Issue by stickylabdev** [realtime-framework/MessagingAndroidChat#4]
When i run the the app it show force close dialog :'( please fix it

**Comment by realtime-framework** [comment]
Can you share more details? An error log would be great.
Thanks.

**Comment by realtime-framework** [comment]
No error details. Closing.

**Comment by stickylabdev** [comment]
Please give me the apk.

**Comment by realtime-framework** [comment]
Send us your Realtime application key for configuration and build. If you don't have one you can get one for free at https://accounts.realtime.co/signup/

**Comment by stickylabdev** [comment]
Application Key: UGXo2h
Private Key: chJV1jxmAAsOAccount Type:Realtime Messaging Free

Rabu, 08 Juli 2015, Realtime Framework notifications@github.com menulis:

**Comment by realtime-framework** [comment]
@muafakul You can download the APK from the following URL: http://storage-public.realtime.co/tmp/RTMChat-release.apk

**Comment by stickylabdev** [comment]
Thanks.

Jumat, 10 Juli 2015, Realtime Framework notifications@github.com menulis:

**Comment by stickylabdev** [comment]
But when i posting ...it doesnot work

Jumat, 10 Juli 2015, shania junianatha sanjuuaa@gmail.com menulis:

**Comment by realtime-framework** [comment]
What doesn't work? Can you give us more details?

It's hard to help you with so little information.

**Comment by stickylabdev** [comment]
I cant reply to others users

Jumat, 10 Juli 2015, Realtime Framework notifications@github.com menulis:

> What doesn't work? Can you give us more details?
> 
> It's hard to help you with so little information.
>

**Comment by realtime-framework** [comment]
What do you mean? You have an error when replying to other users, is that it?

Please give us a fully detailed description of what is the issue otherwise it will be impossible to help you.

**Comment by stickylabdev** [comment]
Have you test the app ?? i iknow ..notyet.

**Comment by realtime-framework** [comment]
Yes we did test it and it's working just fine. So it must be something particular to your device/emulator or network.

If you don't tell us what you are experiencing we can't troubleshoot it.
