### ISSUE TITLE
Sometimes when the app is in background the push notifications are not displayed in the Notification Manager

### ISSUE THREAD

**Issue by jparreira** [realtime-framework/MessagingAndroidChat#6]
Probably something wrong with this code and the underlying state:
https://github.com/realtime-framework/MessagingAndroidChat/blob/4f31e6853e91cb729c9860dd31697f9c10b2e67f/RTMChat/app/src/main/java/services/MyService.java#L52-L57

**Comment by realtime-framework** [comment]
Fixed by pull-request #7
